// Code generated by protoc-gen-go. DO NOT EDIT.
// source: product.proto

package store

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Currency int32

const (
	Currency_RUB Currency = 0
	Currency_USD Currency = 1
	Currency_EUR Currency = 2
)

var Currency_name = map[int32]string{
	0: "RUB",
	1: "USD",
	2: "EUR",
}

var Currency_value = map[string]int32{
	"RUB": 0,
	"USD": 1,
	"EUR": 2,
}

func (x Currency) String() string {
	return proto.EnumName(Currency_name, int32(x))
}

func (Currency) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_f0fd8b59378f44a5, []int{0}
}

type Product struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	IdClient             string   `protobuf:"bytes,2,opt,name=id_client,json=idClient,proto3" json:"id_client,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Currency             Currency `protobuf:"varint,4,opt,name=currency,proto3,enum=store.Currency" json:"currency,omitempty"`
	Price                float32  `protobuf:"fixed32,5,opt,name=price,proto3" json:"price,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Product) Reset()         { *m = Product{} }
func (m *Product) String() string { return proto.CompactTextString(m) }
func (*Product) ProtoMessage()    {}
func (*Product) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0fd8b59378f44a5, []int{0}
}

func (m *Product) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Product.Unmarshal(m, b)
}
func (m *Product) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Product.Marshal(b, m, deterministic)
}
func (m *Product) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Product.Merge(m, src)
}
func (m *Product) XXX_Size() int {
	return xxx_messageInfo_Product.Size(m)
}
func (m *Product) XXX_DiscardUnknown() {
	xxx_messageInfo_Product.DiscardUnknown(m)
}

var xxx_messageInfo_Product proto.InternalMessageInfo

func (m *Product) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Product) GetIdClient() string {
	if m != nil {
		return m.IdClient
	}
	return ""
}

func (m *Product) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Product) GetCurrency() Currency {
	if m != nil {
		return m.Currency
	}
	return Currency_RUB
}

func (m *Product) GetPrice() float32 {
	if m != nil {
		return m.Price
	}
	return 0
}

type Discount struct {
	Error                *Error   `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Id                   uint32   `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Currency             Currency `protobuf:"varint,3,opt,name=currency,proto3,enum=store.Currency" json:"currency,omitempty"`
	Price                float32  `protobuf:"fixed32,4,opt,name=price,proto3" json:"price,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Discount) Reset()         { *m = Discount{} }
func (m *Discount) String() string { return proto.CompactTextString(m) }
func (*Discount) ProtoMessage()    {}
func (*Discount) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0fd8b59378f44a5, []int{1}
}

func (m *Discount) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Discount.Unmarshal(m, b)
}
func (m *Discount) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Discount.Marshal(b, m, deterministic)
}
func (m *Discount) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Discount.Merge(m, src)
}
func (m *Discount) XXX_Size() int {
	return xxx_messageInfo_Discount.Size(m)
}
func (m *Discount) XXX_DiscardUnknown() {
	xxx_messageInfo_Discount.DiscardUnknown(m)
}

var xxx_messageInfo_Discount proto.InternalMessageInfo

func (m *Discount) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *Discount) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Discount) GetCurrency() Currency {
	if m != nil {
		return m.Currency
	}
	return Currency_RUB
}

func (m *Discount) GetPrice() float32 {
	if m != nil {
		return m.Price
	}
	return 0
}

type Error struct {
	State                bool     `protobuf:"varint,1,opt,name=state,proto3" json:"state,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_f0fd8b59378f44a5, []int{2}
}

func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (m *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(m, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetState() bool {
	if m != nil {
		return m.State
	}
	return false
}

func (m *Error) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterEnum("store.Currency", Currency_name, Currency_value)
	proto.RegisterType((*Product)(nil), "store.Product")
	proto.RegisterType((*Discount)(nil), "store.Discount")
	proto.RegisterType((*Error)(nil), "store.Error")
}

func init() { proto.RegisterFile("product.proto", fileDescriptor_f0fd8b59378f44a5) }

var fileDescriptor_f0fd8b59378f44a5 = []byte{
	// 294 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x91, 0x4f, 0x4b, 0xc4, 0x30,
	0x10, 0xc5, 0x37, 0xd9, 0xad, 0xdb, 0x9d, 0x75, 0xff, 0x10, 0x3c, 0x04, 0xbd, 0x94, 0x82, 0x50,
	0x14, 0x16, 0xa9, 0x07, 0xef, 0x76, 0x17, 0xaf, 0x92, 0xa5, 0x67, 0xa9, 0xe9, 0x20, 0x01, 0xb7,
	0x29, 0x69, 0x2a, 0x78, 0xf4, 0x03, 0xf8, 0x9d, 0xa5, 0x69, 0x5a, 0xf6, 0xe8, 0x6d, 0xde, 0xcc,
	0x90, 0xf7, 0x7b, 0x19, 0x58, 0xd5, 0x46, 0x97, 0xad, 0xb4, 0xbb, 0xda, 0x68, 0xab, 0x59, 0xd0,
	0x58, 0x6d, 0x30, 0xfe, 0x25, 0x30, 0x7f, 0xed, 0x07, 0x6c, 0x0d, 0x54, 0x95, 0x9c, 0x44, 0x24,
	0x59, 0x09, 0xaa, 0x4a, 0x76, 0x03, 0x0b, 0x55, 0xbe, 0xc9, 0x4f, 0x85, 0x95, 0xe5, 0x34, 0x22,
	0xc9, 0x42, 0x84, 0xaa, 0xcc, 0x9c, 0x66, 0x0c, 0x66, 0x55, 0x71, 0x42, 0x3e, 0x75, 0x7d, 0x57,
	0xb3, 0x7b, 0x08, 0x65, 0x6b, 0x0c, 0x56, 0xf2, 0x9b, 0xcf, 0x22, 0x92, 0xac, 0xd3, 0xcd, 0xce,
	0xd9, 0xec, 0x32, 0xdf, 0x16, 0xe3, 0x02, 0xbb, 0x82, 0xa0, 0x36, 0x4a, 0x22, 0x0f, 0x22, 0x92,
	0x50, 0xd1, 0x8b, 0xf8, 0x87, 0x40, 0xb8, 0x57, 0x8d, 0xd4, 0x6d, 0x65, 0x59, 0x0c, 0x01, 0x1a,
	0xa3, 0x8d, 0x63, 0x5a, 0xa6, 0x97, 0xfe, 0xb1, 0x43, 0xd7, 0x13, 0xfd, 0xc8, 0x43, 0xd3, 0x11,
	0xfa, 0x9c, 0x61, 0xfa, 0x6f, 0x86, 0xd9, 0x39, 0xc3, 0x13, 0x04, 0xce, 0xa2, 0x1b, 0x37, 0xb6,
	0xb0, 0xe8, 0xfc, 0x43, 0xd1, 0x0b, 0xc6, 0x61, 0x7e, 0xc2, 0xa6, 0x29, 0x3e, 0xd0, 0x7f, 0xca,
	0x20, 0xef, 0x6e, 0x21, 0x1c, 0x4c, 0xd8, 0x1c, 0xa6, 0x22, 0x7f, 0xde, 0x4e, 0xba, 0x22, 0x3f,
	0xee, 0xb7, 0xa4, 0x2b, 0x0e, 0xb9, 0xd8, 0xd2, 0x34, 0x83, 0xcd, 0x10, 0xf1, 0x88, 0xe6, 0x4b,
	0x49, 0x64, 0x0f, 0xb0, 0x7c, 0x41, 0x3b, 0x06, 0x5f, 0x7b, 0x64, 0x7f, 0x99, 0xeb, 0x21, 0xc2,
	0xb0, 0x10, 0x4f, 0xde, 0x2f, 0xdc, 0x19, 0x1f, 0xff, 0x02, 0x00, 0x00, 0xff, 0xff, 0x42, 0x52,
	0x06, 0x5b, 0xd7, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// DiscountServiceClient is the client API for DiscountService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DiscountServiceClient interface {
	GetDiscount(ctx context.Context, in *Product, opts ...grpc.CallOption) (*Discount, error)
}

type discountServiceClient struct {
	cc *grpc.ClientConn
}

func NewDiscountServiceClient(cc *grpc.ClientConn) DiscountServiceClient {
	return &discountServiceClient{cc}
}

func (c *discountServiceClient) GetDiscount(ctx context.Context, in *Product, opts ...grpc.CallOption) (*Discount, error) {
	out := new(Discount)
	err := c.cc.Invoke(ctx, "/store.DiscountService/GetDiscount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DiscountServiceServer is the server API for DiscountService service.
type DiscountServiceServer interface {
	GetDiscount(context.Context, *Product) (*Discount, error)
}

func RegisterDiscountServiceServer(s *grpc.Server, srv DiscountServiceServer) {
	s.RegisterService(&_DiscountService_serviceDesc, srv)
}

func _DiscountService_GetDiscount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Product)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiscountServiceServer).GetDiscount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/store.DiscountService/GetDiscount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiscountServiceServer).GetDiscount(ctx, req.(*Product))
	}
	return interceptor(ctx, in, info, handler)
}

var _DiscountService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "store.DiscountService",
	HandlerType: (*DiscountServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetDiscount",
			Handler:    _DiscountService_GetDiscount_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "product.proto",
}
